### ISSUE TITLE
Confusing names for repo: both tamr-toolbox and tamr_toolbox used in github.io and both names work?

### ISSUE THREAD

**Issue by courtneypk-work** [Datatamer/tamr-toolbox#37]
This was brought to my attention by a customer. On the [home page](https://datatamer.github.io/tamr-toolbox/latest/installation.html) for the tamr-toolbox Guide, the instructions say to use `pip install tamr-toolbox[all]`

<img width="1098" alt="Screen Shot 2021-05-07 at 3 32 26 PM" src="https://user-images.githubusercontent.com/33845596/117500010-0c13d880-af4a-11eb-81f6-b98a425a7ced.png"> 

but then when you click on the link for more installation options, the name of the package changes; the `-` goes to `_`: 

<img width="1052" alt="Screen Shot 2021-05-07 at 3 52 44 PM" src="https://user-images.githubusercontent.com/33845596/117501640-5302cd80-af4c-11eb-9f6f-c13b5a1e9a55.png">

I did the first pip install listed with `-` and this threw an error `no matches found: tamr-toolbox[all]`. I then removed the `[all]` that that worked. I then followed up with `_`, fully expecting there to be an error thrown, but apparently either command works:

> (tuc) paul.courtney@Elements-MacBook-Pro ~ % pip install tamr-toolbox[all]
> zsh: no matches found: tamr-toolbox[all]
> (tuc) paul.courtney@Elements-MacBook-Pro ~ % pip install tamr-toolbox     
> Collecting tamr-toolbox
>   Using cached tamr_toolbox-1.2.0-py3-none-any.whl (71 kB)
> Requirement already satisfied: requests>=2.22 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr-toolbox) (2.25.1)
> Requirement already satisfied: tamr-unify-client>=0.13.0 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr-toolbox) (1.3.0)
> Collecting PyYAML==5.3.1
>   Using cached PyYAML-5.3.1-cp38-cp38-macosx_10_14_x86_64.whl
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr-toolbox) (1.26.4)
> Requirement already satisfied: chardet<5,>=3.0.2 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr-toolbox) (4.0.0)
> Requirement already satisfied: idna<3,>=2.5 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr-toolbox) (2.10)
> Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr-toolbox) (2020.12.5)
> Requirement already satisfied: dataclasses<0.7.0,>=0.6.0 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr-unify-client>=0.13.0->tamr-toolbox) (0.6)
> Installing collected packages: PyYAML, tamr-toolbox
> Successfully installed PyYAML-5.3.1 tamr-toolbox-1.2.0
> (tuc) paul.courtney@Elements-MacBook-Pro ~ % pip install tamr_toolbox
> Requirement already satisfied: tamr_toolbox in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (1.2.0)
> Requirement already satisfied: tamr-unify-client>=0.13.0 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr_toolbox) (1.3.0)
> Requirement already satisfied: requests>=2.22 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr_toolbox) (2.25.1)
> Requirement already satisfied: PyYAML==5.3.1 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr_toolbox) (5.3.1)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr_toolbox) (1.26.4)
> Requirement already satisfied: chardet<5,>=3.0.2 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr_toolbox) (4.0.0)
> Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr_toolbox) (2020.12.5)
> Requirement already satisfied: idna<3,>=2.5 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from requests>=2.22->tamr_toolbox) (2.10)
> Requirement already satisfied: dataclasses<0.7.0,>=0.6.0 in ./.pyenv/versions/3.8.5/envs/tuc/lib/python3.8/site-packages (from tamr-unify-client>=0.13.0->tamr_toolbox) (0.6)
> (tuc) paul.courtney@Elements-MacBook-Pro ~ %

**Comment by along528** [comment]
Thanks Paul for catching and filing this. I've linked the issue to JIRA https://datatamr.atlassian.net/browse/TBOX-174

**Comment by skalish** [comment]
Closed by #38
