### ISSUE TITLE
Repeated lines in example code: https://github.com/Datatamer/tamr-toolbox/blob/develop/examples/snippets/workflow/run_backup_restore.py

### ISSUE THREAD

**Issue by courtneypk-work** [Datatamer/tamr-toolbox#76]
In `run_backup_restore.py` lines 14-16 are repeated in lines 17-19 (see screenshot)

<img width="718" alt="Screen Shot 2022-01-19 at 4 19 49 PM" src="https://user-images.githubusercontent.com/33845596/150215966-3c4f1a17-f9f1-41be-a804-021b9ad5985d.png">

This causes the code shown in github.io to also repeat at https://datatamer.github.io/tamr-toolbox/latest/examples/workflow.html#run-backup-restore (see screenshot)

<img width="745" alt="Screen Shot 2022-01-19 at 4 26 09 PM" src="https://user-images.githubusercontent.com/33845596/150216435-b459de4a-7fff-4508-8cc9-2bd3b3093d8a.png">

**Comment by skalish** [comment]
Thanks @courtneypk-work!  This is now being tracked internally as TBOX-217.
